### ISSUE TITLE
Class bug

### ISSUE THREAD

**Issue by ebanner** [ebanner/pynt#72]
# Code buffer

```python
from django.test import TestCase
from django.urls import reverse


# Create your tests here.

class LuckyIndexViewTests(TestCase):
    def test_webm(self):
        url = reverse('lucky:index')
        response = self.client.get(url)
        html = response.content.decode()
        self.assertIn('webm', html)

    def test_video(self):
        url = reverse('lucky:index')
        response = self.client.get(url)
        html = response.content.decode()
        self.assertIn('webm', html)
```

# pynt.json

```python
{
    "*": [
        "python manage.py runserver 8080"
    ],

    "lucky/tests": [
        "python manage.py test lucky"
    ],

    "lucky/tests.LuckyIndexViewTests.test_webm": [
        "python manage.py test lucky"
    ],

    "lucky/tests.LuckyIndexViewTests.test_video": [
        "python manage.py test lucky"
    ]
}
```

# Namespace

- `lucky/tests.LuckyIndexViewTests.test_video`

# Command

- `pynt-jack-in`

# Result

```python
To connect another client to this kernel, use:
    --existing kernel-75022.json
p.returncode = 0
Traceback (most recent call last):
  File "/Users/ebanner/.anaconda/bin/pynt-embed", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/ebanner/Documents/pynt/bin/pynt-embed", line 85, in <module>
    plac.call(main)
  File "/Users/ebanner/.anaconda/lib/python3.6/site-packages/plac-0.9.6-py3.6.egg/plac_core.py", line 328, in call
    cmd, result = parser.consume(arglist)
  File "/Users/ebanner/.anaconda/lib/python3.6/site-packages/plac-0.9.6-py3.6.egg/plac_core.py", line 207, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/Users/ebanner/Documents/pynt/bin/pynt-embed", line 60, in main
    t = IPythonEmbedder(ns).visit(tree)
  File "/Users/ebanner/.anaconda/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/Users/ebanner/Documents/pynt/codebook/node_transformers.py", line 217, in visit_Module
    module = self.generic_visit(module)
  File "/Users/ebanner/.anaconda/lib/python3.6/ast.py", line 308, in generic_visit
    value = self.visit(value)
  File "/Users/ebanner/.anaconda/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)
  File "/Users/ebanner/Documents/pynt/codebook/node_transformers.py", line 251, in visit_ClassDef
    [idx, method], = [(i, method) for i, method in enumerate(methods) if method.name == self.func_name]
ValueError: not enough values to unpack (expected 1, got 0)
```

**Comment by ebanner** [comment]
Ah, saving the file asked me if I wanted to change the file on disk. Apparently the kernel embed procedure failed to restore the original version of the file. Hence there were no classes to be searched over?
