### ISSUE TITLE
Please state python3 compatibility

### ISSUE THREAD

**Issue by TauPan** [ebanner/pynt#89]
pynt-serve fails for me with python 3.4, because it's using f-strings which were added in python 3.6
```python
> pynt-serve
Traceback (most recent call last):
  File "/home/taupan/nobackup/virtualenvs/myproject/bin/pynt-serve", line 5, in <module>
    import codebook.syntax
  File "/home/taupan/nobackup/virtualenvs/myproject/lib/python3.4/site-packages/codebook/__init__.py", line 29
    open(f"{os.environ['HOME']}/.pynt", 'a').close()
                                     ^
SyntaxError: invalid syntax
```

**Comment by quarkquartet** [comment]
I met that and solved it eventually.
Update my python to python 3.7 (in fact, at the very beginning I use python2).
And at the first step, python3 -m pip install link_to_pynt
Then restart the emacs.
