### ISSUE TITLE
Cannot start pynt mode

### ISSUE THREAD

**Issue by quarkquartet** [ebanner/pynt#91]
Start emacs and open a .py file. it immediately give me this error:
epc:start-server: Server may raise an error. Use "M-x epc:pop-to-last-server-process-buffer RET" to see full traceback:
Traceback (most recent call last):
  File "/usr/local/bin/pynt-serve", line 5, in <module>
    import codebook.syntax
  File "/usr/local/lib/python2.7/site-packages/codebook/__init__.py", line 29
    open(f"{os.environ['HOME']}/.pynt", 'a').close()
                                     ^
SyntaxError: invalid syntax

**Comment by kenkangxgwe** [comment]
Maybe same as #89?
